### ISSUE TITLE
Retrieving data via ODATA Api

### ISSUE THREAD

**Issue by itahirikba** [M-Files/Samples.CustomExternalObjectTypeDataSources#2] opened 2021-09-11 22:25 UTC
Hello,

In the example, in the DataProvider.cs --> GetAll(), you are reading data from local JSON file. 
In our case the data are in ODATA api. To ge the data, we need call a WS which muss contain the static token in the header. 
I thought the connection is done in the Datasource.cs --> OpenConnection method. 
If so, when reading the test project, i do not see any trace of the Datasource.cs --> OpenConnection method.

Any detailed information would be very helpful here. 

Many thanks 
ISA

**Comment by CraigHawker** [comment] 2021-09-13 07:06
Duplicate of issue #1.

**Closed as completed by CraigHawker** 2021-09-13 07:06 UTC
